allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260623.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260623.1'
  - '@cloudflare/workerd-linux-64@1.20260623.1'
  - '@cloudflare/workerd-linux-arm64@1.20260623.1'
  - '@cloudflare/workerd-windows-64@1.20260623.1'
  - miniflare@4.20260623.0
  - workerd@1.20260623.1
  - wrangler@4.104.0
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
